import { useEffect, useMemo, useState } from 'react'

const properties = [
  { id: 1, title: 'Casa Atlântica', type: 'Casa', city: 'Praia do Forte, BA', price: 2850000, area: 318, beds: 4, baths: 5, parking: 3, tag: 'Oferta especial', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85', description: 'Uma casa solar, cercada por verde e a poucos minutos do mar. Arquitetura brasileira contemporânea com integração total entre sala, jardim e piscina.' },
  { id: 2, title: 'Lume 302', type: 'Apartamento', city: 'Pinheiros, São Paulo', price: 1480000, area: 112, beds: 2, baths: 2, parking: 2, tag: 'Novo', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85', description: 'Apartamento autoral em edifício boutique, com marcenaria desenhada sob medida, varanda generosa e luz natural durante todo o dia.' },
  { id: 3, title: 'Refúgio Mantiqueira', type: 'Chácara', city: 'São Bento do Sapucaí, SP', price: 1950000, area: 420, beds: 3, baths: 4, parking: 4, tag: 'Mais buscado', image: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1400&q=85', description: 'Casa-refúgio com vista para as montanhas, lareira, ateliê e uma implantação que respeita o desenho natural do terreno.' },
  { id: 4, title: 'Casa Amarela', type: 'Casa', city: 'Vila Madalena, São Paulo', price: 2200000, area: 205, beds: 3, baths: 3, parking: 2, tag: 'Curadoria', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85', description: 'Casa urbana com jardim interno, volumes bem iluminados e uma atmosfera que equilibra design e vida cotidiana.' },
  { id: 5, title: 'Vista Ibirapuera', type: 'Apartamento', city: 'Moema, São Paulo', price: 3100000, area: 180, beds: 3, baths: 4, parking: 3, tag: 'Vista aberta', image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=85', description: 'Planta fluida com vista para o verde, acabamentos atemporais e infraestrutura completa para receber.' },
  { id: 6, title: 'Casa Brisa', type: 'Casa', city: 'Trancoso, BA', price: 4200000, area: 390, beds: 5, baths: 6, parking: 2, tag: 'Lançamento', image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=85', description: 'Um endereço para desacelerar: linhas orgânicas, piscina emoldurada por palmeiras e acesso reservado à praia.' },
]
const brl = value => `R$ ${value.toLocaleString('pt-BR')}`
const categories = [['⌂', 'Casas'], ['▣', 'Apartamentos'], ['⌁', 'Praia'], ['♧', 'Campo'], ['⌖', 'São Paulo'], ['✦', 'Lançamentos']]
const banners = [
  { eyebrow: 'Semana do lar', title: 'Encontre um lugar\npara chamar de seu.', text: 'Condições especiais em imóveis selecionados.', image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=88', button: 'Ver oportunidades' },
  { eyebrow: 'Curadoria Imobloom', title: 'Endereços que\ncombinam com você.', text: 'Casas, apartamentos e refúgios escolhidos com cuidado.', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=88', button: 'Explorar coleção' },
  { eyebrow: 'Morar bem', title: 'Seu próximo capítulo\ncomeça aqui.', text: 'Descubra imóveis com alma em todo o Brasil.', image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=88', button: 'Buscar meu imóvel' },
]

function Brand() { return <a className="brand official-brand" href="#topo" aria-label="Hiper Stok início"><img src="/assets/hiper-stok-logo.png" alt="Hiper Stok" /></a> }
function Eyebrow({ children }) { return <p className="eyebrow">{children}</p> }
function PropertyCard({ property, onFavorite, favorites, onDetail }) { return <article className="property-card catalog-card reveal"><div className="card-image"><img src={property.image} alt={property.title}/><span className="tag">{property.tag}</span><button className={`favorite ${favorites.has(property.id) ? 'active' : ''}`} onClick={() => onFavorite(property.id)} aria-label={`Favoritar ${property.title}`}>{favorites.has(property.id) ? '♥' : '♡'}</button><button className="view-detail" onClick={() => onDetail(property.id)}>Ver detalhes ↗</button></div><div className="card-content"><p className="card-location">⌖ {property.city}</p><h3>{property.title}</h3><div className="card-meta"><span>{property.area} m²</span><span>{property.beds} quartos</span><span>{property.parking} vagas</span></div><strong className="price">{brl(property.price)}</strong><button className="card-link" onClick={() => onDetail(property.id)}>Conferir imóvel <span>→</span></button></div></article> }

export default function App() {
  const [favorites, setFavorites] = useState(() => new Set(JSON.parse(localStorage.getItem('imobloom-favorites') || '[]')))
  const [type, setType] = useState('Todos'); const [city, setCity] = useState(''); const [query, setQuery] = useState({ type: 'Todos', city: '' })
  const [modalProperty, setModalProperty] = useState(null); const [toast, setToast] = useState(''); const [slide, setSlide] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [sent, setSent] = useState(false)
  const filtered = useMemo(() => properties.filter(p => (query.type === 'Todos' || query.type === 'Favoritos' || p.type === query.type) && (!query.city || p.city.toLowerCase().includes(query.city.toLowerCase())) && (query.type !== 'Favoritos' || favorites.has(p.id))), [query, favorites])
  const notify = message => { setToast(message); window.clearTimeout(window.toastTimer); window.toastTimer = window.setTimeout(() => setToast(''), 2600) }
  const toggleFavorite = id => { setFavorites(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); localStorage.setItem('imobloom-favorites', JSON.stringify([...next])); return next }); notify(favorites.has(id) ? 'Imóvel removido dos favoritos.' : 'Imóvel salvo nos favoritos.') }
  const search = e => { e.preventDefault(); setQuery({ type, city }); document.querySelector('#catalogo').scrollIntoView({ behavior: 'smooth' }); notify('Busca atualizada.') }
  useEffect(() => { const timer = window.setInterval(() => setSlide(current => (current + 1) % banners.length), 6000); return () => window.clearInterval(timer) }, [])
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target) } }), { threshold: .1 }); document.querySelectorAll('.reveal').forEach((el, i) => { el.style.transitionDelay = `${Math.min(i * 35, 220)}ms`; observer.observe(el) }); return () => observer.disconnect() }, [filtered.length, slide])
  const goCategory = value => { setType(value); setQuery({ type: value, city: '' }); document.querySelector('#catalogo').scrollIntoView({ behavior: 'smooth' }) }

  return <>
    <div className="commerce-top"><span>Até 10% de desconto em imóveis selecionados</span><span>Atendimento pelo WhatsApp</span><span>Visitas sem compromisso</span></div>
    <header className="market-header" id="topo"><Brand/><form className="market-search" onSubmit={search}><input value={city} onChange={e => setCity(e.target.value)} placeholder="Busque por cidade, bairro ou tipo de imóvel"/><button aria-label="Buscar">⌕</button></form><div className="market-actions"><button onClick={() => notify('Entre ou crie sua conta para acompanhar seus imóveis.')}><span>♙</span><small>Olá, entre<br/><b>ou crie sua conta</b></small></button><button onClick={() => { setQuery({ type: 'Favoritos', city: '' }); document.querySelector('#catalogo').scrollIntoView({ behavior: 'smooth' }) }}><span>♡</span><small>Meus<br/><b>favoritos</b></small><em>{favorites.size}</em></button><button onClick={() => notify('Sua lista de visita está vazia.')}><span>▱</span><small>Minha<br/><b>lista</b></small></button></div><button className="menu-btn" onClick={() => setMenuOpen(v => !v)} aria-label="Menu">☰</button></header>
    <nav className={`market-nav ${menuOpen ? 'open' : ''}`}><a href="#catalogo">Departamentos</a><a href="#ofertas">Ofertas do dia</a><a href="#catalogo">Casas</a><a href="#catalogo">Apartamentos</a><a href="#catalogo">Imóveis de praia</a><a href="#como-funciona">Serviços</a><a href="#contato">Ajuda</a></nav>
    <main>
      <section className="market-hero"><img src={banners[slide].image} alt=""/><div className="market-hero-overlay"><Eyebrow>{banners[slide].eyebrow}</Eyebrow><h1>{banners[slide].title.split('\n').map((line, i) => <span key={line}>{line}{i === 0 && <br/>}</span>)}</h1><p>{banners[slide].text}</p><a className="primary-btn" href="#catalogo">{banners[slide].button} <span>↗</span></a></div><button className="hero-arrow prev" onClick={() => setSlide((slide - 1 + banners.length) % banners.length)}>←</button><button className="hero-arrow next" onClick={() => setSlide((slide + 1) % banners.length)}>→</button><div className="hero-dots">{banners.map((banner, i) => <button key={banner.eyebrow} className={i === slide ? 'active' : ''} onClick={() => setSlide(i)}/>)}</div></section>
      <section className="category-row"><div className="category-title"><Eyebrow>Encontre mais rápido</Eyebrow><h2>Compre por categoria</h2></div><div className="category-list">{categories.map(([icon, name]) => <button key={name} onClick={() => goCategory(name === 'Casas' ? 'Casa' : name === 'Apartamentos' ? 'Apartamento' : 'Todos')}><span>{icon}</span><b>{name}</b></button>)}</div></section>
      <section className="benefit-row"><div><b>Curadoria de verdade</b><span>Imóveis selecionados por especialistas</span></div><div><b>Compra tranquila</b><span>Suporte em cada etapa da decisão</span></div><div><b>Visita sem pressa</b><span>Agende no seu ritmo, sem compromisso</span></div><div><b>Pagamento seguro</b><span>Negociação clara e transparente</span></div></section>
      <section className="deal-section" id="ofertas"><div className="section-heading"><div><Eyebrow>Oportunidades da semana</Eyebrow><h2>Ofertas que valem <em>conhecer</em></h2></div><a className="text-link" href="#catalogo">Ver todas <span>↗</span></a></div><div className="deal-grid">{properties.slice(0, 3).map((p, i) => <div className="deal-banner" key={p.id} style={{ backgroundImage: `linear-gradient(90deg, #1d2927dd, transparent), url(${p.image})` }}><div><small>{i === 0 ? 'ATÉ 10% OFF' : 'IMÓVEL EM DESTAQUE'}</small><h3>{p.title}</h3><p>{p.city}</p><button onClick={() => setModalProperty(p)}>Ver oportunidade ↗</button></div></div>)}</div></section>
      <section className="catalog-section" id="catalogo"><div className="section-heading"><div><Eyebrow>Seleção para você</Eyebrow><h2>Imóveis mais <em>buscados</em></h2></div><div className="sort-pill"><span>{filtered.length} imóveis encontrados</span><select><option>Mais relevantes</option><option>Menor preço</option><option>Maior preço</option></select></div></div><div className="catalog-grid">{filtered.map(p => <PropertyCard key={p.id} property={p} favorites={favorites} onFavorite={toggleFavorite} onDetail={id => setModalProperty(properties.find(p => p.id === id))}/>)}</div>{!filtered.length && <div className="empty-state" style={{ display: 'block' }}>Nenhum imóvel encontrado. <button onClick={() => { setQuery({ type: 'Todos', city: '' }); setType('Todos'); setCity('') }}>Limpar filtros</button></div>}</section>
      <section className="manifesto" id="como-funciona"><div className="manifesto-image reveal"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85" alt="Fachada de casa contemporânea cercada por verde"/><div className="stamp">IM<br/>BL</div></div><div className="manifesto-copy reveal"><Eyebrow>Nosso jeito de fazer</Eyebrow><h2>Escolher onde viver<br/><em>pode ser leve.</em></h2><p>Nem todo imóvel vira lar. Por isso, cada endereço que entra na Imobloom passa por um olhar atento e uma negociação transparente.</p><div className="steps"><div><span>01</span><p><strong>Descobrir</strong><br/>Conte o que faz seu olho brilhar.</p></div><div><span>02</span><p><strong>Comparar</strong><br/>Veja detalhes, preços e localização.</p></div><div><span>03</span><p><strong>Visitar</strong><br/>Agende sem pressão e decida no seu tempo.</p></div></div></div></section>
      <section className="contact-section" id="contato"><div><Eyebrow>Vamos conversar</Eyebrow><h2>Seu lugar no mundo<br/><em>pode estar aqui.</em></h2><p>Deixe seus dados e um especialista entra em contato para entender o que você procura.</p></div><form onSubmit={e => { e.preventDefault(); e.currentTarget.reset(); setSent(true); notify('Contato enviado com sucesso.') }}><label>Seu nome<input required placeholder="Como podemos te chamar?"/></label><label>Seu melhor e-mail<input required type="email" placeholder="voce@email.com"/></label><label>O que você procura?<select><option>Quero comprar</option><option>Quero alugar</option></select></label><button className="primary-btn">Quero ser encontrado <span>↗</span></button>{sent && <p className="form-success show">Recebemos seu contato. Em breve a gente conversa.</p>}</form></section>
    </main>
    <footer><Brand/><p>Imóveis com alma, para histórias de verdade.</p><div className="footer-links"><a href="#catalogo">Imóveis</a><a href="#como-funciona">Sobre nós</a><a href="#contato">Contato</a></div><small>© {new Date().getFullYear()} Imobloom. Feito para florescer.</small></footer>
    {modalProperty && <div className="modal open" role="dialog" aria-modal="true"><div className="modal-backdrop" onClick={() => setModalProperty(null)}/><div className="modal-card"><button className="modal-close" onClick={() => setModalProperty(null)}>×</button><img src={modalProperty.image} alt={modalProperty.title}/><div className="modal-info"><Eyebrow>⌖ {modalProperty.city}</Eyebrow><h2>{modalProperty.title}</h2><p>{modalProperty.description}</p><div className="modal-stats"><span>{modalProperty.area} m²</span><span>{modalProperty.beds} quartos</span><span>{modalProperty.baths} banheiros</span><span>{modalProperty.parking} vagas</span></div><strong className="price">{brl(modalProperty.price)}</strong><a className="primary-btn" href="#contato" onClick={() => setModalProperty(null)}>Tenho interesse <span>↗</span></a></div></div></div>}
    <div className={`toast ${toast ? 'show' : ''}`}>{toast}</div>
  </>
}
